Repository Block-Fighters/missionbrothers-client, pull requests merged in 2023-06, with the labels that each got.

#2 [#1]chore:초기환경셋팅
  package-lock.json
  package.json
  yarn.lock
Labels: ⚙️Chore

#5 [#4]chore: hardhat setting
  hardhat/.gitignore
  hardhat/README.md
  hardhat/contracts/MissionBro.sol
  hardhat/contracts/Token.sol
  hardhat/hardhat.config.js
  hardhat/package-lock.json
  hardhat/package.json
  hardhat/scripts/deploy.js
  hardhat/test/Lock.js
  package-lock.json
  package.json
  src/abi/MissionBro.json
  src/abi/Token.json
  yarn.lock
Labels: ⚙️Chore

#7 Style/#6
  package-lock.json
  package.json
  src/components/layout/Header.jsx
  src/components/layout/style.js
  yarn.lock
Labels: 🎨Style

#10 [#8]feature:미션등록버튼 기능구현
  src/App.jsx
  src/Router.jsx
  src/components/layout/Header/Header.jsx
  src/components/layout/Header/style.js
  src/components/layout/Layout.jsx
  src/components/layout/RegisterMissonButton/RegisterMissionButton.jsx
  src/components/layout/RegisterMissonButton/style.js
  src/pages/Main/index.jsx
  src/pages/RegisterMission/index.jsx
Labels: ✨Feature

#17 [#16]Feature:TokenContract MissionContract update
  hardhat/contracts/MissionBro.sol
  hardhat/contracts/Token.sol
Labels: ✨Feature

#19 [#11]style:Header 및 Card 스타일 수정
  src/components/MissionCard/Card.jsx
  src/components/MissionCard/style.js
  src/components/layout/Header/style.js
  src/components/layout/RegisterMissonButton/style.js
Labels: 🎨Style

#22 [#21]Feature:add participate function
  hardhat/contracts/MissionBro.sol
Labels: ✨Feature

#24 [#23]Feature: add transferToContractAndClaimEther function
  hardhat/contracts/Token.sol
Labels: ✨Feature

#26 [#25]Feature: modify participateInMission function
  hardhat/contracts/MissionBro.sol
Labels: ✨Feature

#27 [#20]style:Main 페이지 목업 및 nav 이동 및 무한 스크롤 구현
  src/components/Main/MissionCard/CompletedMission.jsx
  src/components/Main/MissionCard/CompletedMissionData.js
  src/components/Main/MissionCard/ProgressingMission.jsx
  src/components/Main/MissionCard/ProgressingMissionData.js
  src/components/Main/MissionCard/RecruitingMission.jsx
  src/components/Main/MissionCard/RecruitingMissionData.js
  src/components/Main/MissionCard/style.js
  src/components/MissionCard/Card.jsx
  src/components/MissionCard/style.js
  src/pages/Main/index.jsx
  src/pages/Main/style.js
Labels: ✨Feature, 🎨Style

#29 [#28]Feature:add reward function
  hardhat/contracts/MissionBro.sol
Labels: ✨Feature

#32 [#31]Deploy: modify contracts deploy
  hardhat/scripts/deploy.js
  src/abi/MissionBro.json
  src/abi/Token.json
  yarn.lock
Labels: 🌏Deploy

#34 [#33]Feature: 보안강화 및 중복참여 방지
  hardhat/contracts/MissionBro.sol
Labels: ✨Feature

#38 [#37]Deploy: update abi file
  src/abi/MissionBro.json
  src/abi/Token.json
Labels: 🌏Deploy

#43 [#30]feature:미션등록페이지 목업 및 기능 구현
  .eslintrc.js
  package.json
  src/components/ImageLoader/ImageLoader.jsx
  src/components/ImageLoader/style.js
  src/components/layout/Header/style.js
  src/hooks/getToday.js
  src/hooks/makeTimeStamp.js
  src/hooks/useCheckFile.js
  src/pages/Main/style.js
  src/pages/RegisterMission/index.jsx
  src/pages/RegisterMission/style.js
  yarn.lock
Labels: ✨Feature, 🎨Style

#45 Bugfix/#44 미션 등록 페이지 이동 시 스크롤 중간부터 시작되는 에러
  src/pages/RegisterMission/index.jsx
  yarn.lock
Labels: 🐞BugFix

#47 [#46]axios 설치
  package.json
  yarn.lock
Labels: ⚙️Chore

#55 [#48]feature:지갑 로그인 구현
  package.json
  src/App.jsx
  src/components/ConnectWalletButton/ConnectWalletButton.jsx
  src/components/ConnectWalletButton/style.js
  src/components/Provider/WagmiProvider.jsx
  src/components/layout/Header/Header.jsx
  src/components/layout/Header/style.js
  src/pages/RegisterMission/index.jsx
  src/wagmi.js
  yarn.lock
Labels: ✨Feature

#57 컨트랙트 연결
  src/components/layout/Header/Header.jsx
  src/utils/getContract.js
Labels: ✨Feature

#71 [#70]bugfix: 미션등록 버그 수정
  src/abi/MissionBro.json
  src/abi/Token.json
  src/pages/RegisterMission/index.jsx
Labels: 🐞BugFix

#73 [#72]feature:상세페이지 BRO
  src/components/Join/JoinSticky.jsx
  src/pages/Detail/MissionDetail.jsx
Labels: ✨Feature

#77 [#76]style: add photo card
  src/Router.jsx
  src/pages/Members/App.css
  src/pages/Members/Members.jsx
Labels: 🎨Style

#79 [#78]Refactoring: contracts refactoring
  hardhat/contracts/MissionBro.sol
  hardhat/contracts/Token.sol
Labels: 🛠️Refactoring

#81 [#80]feature:토큰구매시 approve기능 추가
  src/pages/MyPage/index.jsx
Labels: ✨Feature

#83 [#82]feature:participateInMission함수 web3js로 연동
  src/components/Button/JoinButton.jsx
  src/components/Join/JoinSticky.jsx
  src/pages/Detail/MissionDetail.jsx
Labels: ✨Feature

#87 [#86]BugFix:모달 수정
  src/components/ConnectWalletButton/ConnectWalletButton.jsx
Labels: 🐞BugFix

#89 [#88]Feature:wei단위로 바꿔서 미션등록
  package.json
  src/pages/Detail/MissionDetail.jsx
  src/pages/RegisterMission/index.jsx
Labels: ✨Feature

#91 [#90]BugFix:미션등록할 때 트랜잭션 수정
  src/components/Button/JoinButton.jsx
  src/index.jsx
  src/pages/Detail/MissionDetail.jsx
  src/pages/RegisterMission/index.jsx
  src/wagmi.js
  yarn.lock
Labels: 🐞BugFix
